name: 'Reliably CLI Actions'
description: 'Use Reliably in your GitHub workflow'
author: 'Reliably'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  python-version:
    description: "Which Python version to use (should be 3.10+)"
    required: false
    default: '3.10'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: reliablyhq/actions/setup@v0
        with:
          python-version: ${{ inputs.python-version }}
          reliably-version: ${{ inputs.reliably-version }}
          reliably-config-path: ${{ inputs.reliably-config-path }}
