name: 'Reliably Plan Workflow'
description: 'Run a Reliably Plan'
author: 'Reliably'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  github-token:
    description: "The GitHub token to commit the results"
    required: true
  reliably-agent-token:
    description: "Reliably agent authentication token"
    required: false
  reliably-service-token:
    description: "Reliably service (user) authentication token"
    required: true
  working-dir:
    description: "The directory where the plan will be run from"
    required: true
  experiment-url:
    description: "The full URL to the experiment"
    required: true
  plan-id:
    description: "The identifier of the executed plan"
    required: true
  org-id:
    description: "The identifier of the organization owning the plan"
    required: true
  reliably-experiment-extra:
    description: "A json encoded object to be added to the result of the run"
    required: false
  python-version:
    description: "The python version to use"
    required: false
    default: "3.10"
  reliably-host:
    description: "The hostname of the Reliably server"
    required: false
    default: "app.reliably.com"
runs:
  using: "composite"
  steps:
    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - name: Install Chaos Toolkit
      shell: bash
      run: |
        python -m pip install -q --prefer-binary -U wheel setuptools pip
        python -m pip install -q --prefer-binary -U chaostoolkit \
          chaostoolkit-aws \
          chaostoolkit-azure \
          chaostoolkit-kubernetes \
          chaostoolkit-google-cloud-platform \
          chaostoolkit-humio \
          chaostoolkit-prometheus \
          chaostoolkit-toxiproxy \
          chaostoolkit-opentracing \
          chaostoolkit-istio \
          chaostoolkit-wiremock \
          chaostoolkit-gandi \
          chaostoolkit-dynatrace \
          chaostoolkit-k6 \
          chaostoolkit-addons \
          chaostoolkit-grafana \
          chaostoolkit-slack \
          chaostoolkit-reliably \
          opentelemetry-api \
          opentelemetry-sdk \
          opentelemetry-instrumentation-httpx \
          opentelemetry-instrumentation-logging \
          opentelemetry-exporter-otlp-proto-http \
          opentelemetry-opentracing-shim \
          opentelemetry-propagator-b3 \
          opentelemetry-semantic-conventions \
          opentelemetry-exporter-gcp-trace \
          opentelemetry-resourcedetector-gcp \
          opentelemetry-propagator-gcp \
          httpx[http2]
        python -m pip install -q --prefer-binary -U reliably-cli


    - name: Add repository top-level ~/bin directory to the PATH
      shell: bash
      run: |
        if [[ -d "~/bin" ]]; then
          echo "Adding ~/bin to PATH"
          echo "PATH=$PATH:~/bin" >> $GITHUB_ENV
        fi

    - name: Create directory to hold results and logs
      shell: bash
      run: mkdir -p ${{ inputs.working-dir }}

    - name: Run
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      run: |
        echo 'RELIABLY_EXECUTION_EXTRA=${{ inputs.reliably-experiment-extra }}' >> $GITHUB_ENV
        reliably service plan execute --log-file run.log --result-file run.json ${{ inputs.plan-id }}
      env:
        CHAOSTOOLKIT_LOADER_AUTH_BEARER_TOKEN: ${{ inputs.reliably-service-token }}
        RELIABLY_TOKEN: ${{ inputs.reliably-service-token }}
        RELIABLY_AGENT_TOKEN: ${{ inputs.reliably-agent-token }}
        RELIABLY_SERVICE_TOKEN: ${{ inputs.reliably-service-token }}
        RELIABLY_ORGANIZATION_ID: ${{ inputs.org-id }}
        RELIABLY_HOST: ${{ inputs.reliably-host }}
        RELIABLY_SERVICE_HOST: https://${{ inputs.reliably-host }}

    - name: Store results
      if: success() || failure()
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      run: |
        export EXECUTION_URL=$(cat run.json | jq -r '.experiment.extensions[] | select(.name=="reliably") | .execution_url')

        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -s -m "Plan ${{ inputs.plan-id }} execution" -m "Visit ${EXECUTION_URL}"
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_ACTOR: ${{ github.actor }}


