name: 'Reliably Experiment Action'
description: 'Run a Reliably Chaos Toolkit experiment'
author: 'Reliably'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  reliably-agent-token:
    description: "Reliably agent authentication token"
    required: true
  reliably-experiment-url:
    description: "Reliably experiment url"
    required: true
  python-version:
    description: "The python version to use to run the Chaos Toolkit"
    required: false
    default: "3.10"
  environment-name:
    description: "Name of a GitHub environment to populate secrets from"
    required: false
  working-dir:
    description: "The directory where the plan will be run from"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - name: Install Chaos Toolkit
      shell: bash
      run: |
        python -m pip install -q --prefer-binary -U wheel setuptools pip
        python -m pip install -q --prefer-binary chaostoolkit \
          chaostoolkit-aws \
          chaostoolkit-azure \
          chaostoolkit-kubernetes \
          chaostoolkit-google-cloud-platform \
          chaostoolkit-humio \
          chaostoolkit-prometheus \
          chaostoolkit-toxiproxy \
          chaostoolkit-opentracing \
          chaostoolkit-istio \
          chaostoolkit-wiremock \
          chaostoolkit-gandi \
          chaostoolkit-dynatrace \
          chaostoolkit-k6 \
          chaostoolkit-addons \
          chaostoolkit-grafana \
          chaostoolkit-slack \
          git+https://github.com/chaostoolkit-incubator/chaostoolkit-reliably@master#chaostoolkit-reliably \
          opentelemetry-api \
          opentelemetry-sdk \
          opentelemetry-exporter-otlp-proto-http \
          opentelemetry-propagator-b3 \
          opentelemetry-semantic-conventions

    - name: Add repository top-level ~/bin directory to the PATH
      shell: bash
      run: |
        if [[ -d "~/bin" ]]; then
          echo "Adding ~/bin to PATH"
          echo "PATH=$PATH:~/bin" >> $GITHUB_ENV
        fi

    - name: Inject Reliably environment variables, if any, into workflow
      shell: bash
      run: |
        echo "Loading ${{ inputs.working-dir }}/.reliably.env into GITHUB_ENV"
        cd ${{ inputs.working-dir }}
        if [[ -f "./.reliably.env" ]]; then
          while IFS= read -r line
          do
            echo "$line" >> $GITHUB_ENV
          done < "./.reliably.env"
        fi
